---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mosquitto
  namespace: mosquitto
spec:
  interval: 5m
  chart:
    spec:
      chart: mosquitto
      version: 4.2.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    env:
      TZ: "Melbourne/Australia"
    persistence:
      data:
        enabled: true
        storageClass: longhorn
        size: 1Gi
        mountPath: /mosquitto/data
      configinc:
        enabled: true
        mountPath: /mosquitto/configinc
        accessMode: ReadWriteOnce
        size: 100Mi
        storageClass: longhorn
