---
apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: external-transmission
  name: external-transmission
  namespace: external-services
spec:
  type: ExternalName
  ports:
    - name: external-transmission
      port: 80
      targetPort: 9091
  externalName: 192.168.1.212
