---
kubernetes:
  children:
    master:
      hosts:
        c1:
          ansible_host: 192.168.1.221
        c2:
          ansible_host: 192.168.1.222
        c3:
          ansible_host: 192.168.1.223
    worker:
      hosts:
        w1:
          ansible_host: 192.168.1.231
        w2:
          ansible_host: 192.168.1.232
