apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ingressroute-unifi-stun
  namespace: unifi
spec:
  entryPoints:
    - unifistun
  routes:
  - kind: Rule
    match: Host(`unifi.${SECRET_DOMAIN}`) && PathPrefix(`/inform`)
    services:
    - name: unifi-udp
      port: stun 