apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ingressroute-unifi-commms
  namespace: unifi
spec:
  entryPoints:
    - unifiinform
  routes:
    - kind: Rule
      match: Host(`unifi.${SECRET_DOMAIN}`) && PathPrefix(`/inform`)
      services:
        - name: unifi
          port: 8080
