---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: external-adguard-1-ingress
  namespace: external-services
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`adguard-1.${SECRET_DOMAIN}`)
      kind: Rule
      services:
        - name: external-adguard-1
          kind: Service
          port: 8090
          passHostHeader: true
  tls:
    secretName: wildcard-tls
