---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - service.yaml
  - ingress.yaml
  - service-1.yaml
  - ingress-1.yaml
  - service-2.yaml
  - ingress-2.yaml
  - service-3.yaml
  - ingress-3.yaml
