# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:BEP0KVGYCmz3NIUTcdzdKJ8=,iv:0jWUcKaEGDMsfhxqA85Q1gpwXzpEYudrBdtCQo3OjE0=,tag:Gm93tLVZhsPfoJkbjlphRw==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:uHYz+++pVDhmEBPnF4BUxDhyegeTaUQ=,iv:Y1xROBuN9/I7Fah7+Mlw6SAd2IKgN9hEk6gjVm7gvMk=,tag:J5sI35sOVD0vma0QGgPnvQ==,type:str]
    CAMERA_1_PASSWORD: ENC[AES256_GCM,data:4Dmfmb6i,iv:8gAYJFaZZQh0ljgqAQA5DzmiDORA04z/Bm5ylfAsxMM=,tag:t2reevqSItd1hG++0iE63w==,type:str]
    CAMERA_2_PASSWORD: ENC[AES256_GCM,data:8C5IMmNh,iv:MzZAWMw40e0oI8lb8asuzQO7+1a81hot8X8fZgja688=,tag:5kh9q+bjp8NpxM9Mm4C19w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1982zla5xqalhvmpkp6dmw6y55k4tdez2p9ygclnt64sxrucxds3sumda9e
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByUFYzYXN6Skd3RVFUeVhL
            Qnc5WmE3NkFYL2QwclBRZjE4QytCU0V4SmpJCmFRdllQVUxVRlhYNUpmREkrbTFl
            Y3NFdnoyL2hoVDVBRjVsWk9wMzFVWWMKLS0tIFJ1UHZWdVN0Q1BQT3RUOHJVdVNq
            K1dYcWxuelZWdllFOHp2WlNkMmRrLzgKlGojN9i/w5EZl+3/IOJpFIeA79AyGcQu
            imTFvOxDu/3/Z2bfg9KlNCjBmfyA+zedRZY5JutqW6EMAs6TKmJDCA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-03-14T11:35:08Z"
    mac: ENC[AES256_GCM,data:kO9cMisMzitDp4uYmFaWEmpRsUEewuxKXvNyjO9Mij/kvK9P7BhESNQ7xC435LthI4zmi8+VauxiWFBSbB3oAr7D5nBqPiliB9SR2tjsmhpEeFXuq+ldKsyZweJzOC9580vBF2IvmgLdCG3fIzBHTJAuHTeFuB29WFftzCisKWU=,iv:eewSgqFF+VILDPQK92tuKGp4UUSKbnDrFznmpPbquCQ=,tag:h/YtM96VaxCoiJ+Z19oFXw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
