---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: csi-driver-smb
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: csi-driver-smb
      version: v1.7.0
      sourceRef:
        kind: HelmRepository
        name: csi-driver-smb-charts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    controller.runOnMaster: true
