---
apiVersion: v1
data:
    password: ENC[AES256_GCM,data:2e/i9JIMuxr0TB56aIFJ4vEAUkr0HsK/x6Cw+Gg3NflKL8FCcupgewj2W/SWbRw2I+tT+OLafWQ=,iv:RdADJ7k4JnHGJnHhdKpDhqWCrwZczWauo4OLV5+yg1M=,tag:kx1ei2yZso9281ikhHCWmQ==,type:str]
    username: ENC[AES256_GCM,data:NuZYG/QBkt2if9SMLJnDvhfJyzEZA9nH,iv:MPAxIGSwa+qdWwQNA5vyPt2XQyI32S48EqTlIJZeFUE=,tag:yt7GMnTT6E7pT5JMQWTVJg==,type:str]
kind: Secret
metadata:
    name: smbcreds
    namespace: default
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1982zla5xqalhvmpkp6dmw6y55k4tdez2p9ygclnt64sxrucxds3sumda9e
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiVkV1WVM5aEdEdkxzay9k
            bkVHRnlKZnpxSno1MHhpbUZUbERQUmh0TndBCit2ejk2M0RsaDc0TlE3UVVteEZQ
            ZVFkUUJ4L3NIcDhrU25IdXdENUQ1U28KLS0tIHFhMitIS0c5QXE1Zmt3dndNMy91
            MEQxNFZJRzhTV1ExeWtEQmVMUEhqL0kKlJ5nEAaiizcSfq5fUC4SxGgaoaBCucKR
            Gwq5AFWzJhbYDhaSJ5CBNZUI0GBZ0evlUuy3U5A5u9GePeEiMSa0jw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-03-09T10:04:16Z"
    mac: ENC[AES256_GCM,data:zF2+Ll3QyFKnP5peUDRGMKqm13hCNw4RBGzyK2BWRNjLaZtmM5QRC+9LKcSfvr3cKLTQLZiwv1hnKulW2DnPNu5BmYFN5A8sTQew6F0Cch+Xn1+17ocIq8hD0IRHbDJd+pux1by1cFmICumud6vv9Auqx7Jkg56ZmxZj4rwiB7Q=,iv:3wcYE+LOaZqPJEMorbNwjVzNf67dNYfHf0ChPi5HoOk=,tag:vk/9l4wpq00c15reokywjQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
