---
name: Check YAML and Ansible Lint

on:
  push:
    tags_ignore:
      - "*"
  pull_request:

jobs:
  yamllint:
    runs-on: ubuntu-20.04
    name: yaml-lint
    steps:
      - uses: actions/checkout@v2
      - name: yamllint
        uses: ibiqlik/action-yamllint@v3
  ansiblelint:
    runs-on: ubuntu-latest
    name: ansible-lint
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v2
      - run: pip install ansible ansible-lint
      - run: ansible-lint --version
      - run: ansible-lint .
