---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prowlarr-pvc-config
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 128Mi
